id: 738286ddff474a62892620229051dc71
initial_creation_type: ocr
source_metadata:
  volumes:
    b353590c2a494e78bb5d9c9a9a4627ba:
      base_file: v076.txt
      image_group_id: I1PD95922
      title: ''
      total_pages: 1517
      volume_number: 77
